#TODO: Change version

version: 'v1..{build}'

cache:
  - model
  - Package
  
environment:
  STOREPASS:
    secure: l9BZEU39F1a4vSkhwl0CHR+yh6CD1c7byGzMv+1NUa4=
  QT_USER:
    secure: EoBPaPuJ6u9UDYpQWjKhUg==
  QT_PASSWORD:
    secure: ejAYGgB+3sBispRxUSr0xw==

  matrix:
  ##### msvc 2019 ########
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATORS: "Visual Studio 16 2019"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 16
    QT_ROOT: C:\Qt\5.12\msvc2019
    BUILD_ARCH: x86

  ##### msvc 2017 ########
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 15 2017"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    QT_ROOT: C:\Qt\5.12\msvc2017
    BUILD_ARCH: x86
  
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 15 2017 Win64"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    QT_ROOT: C:\Qt\5.12\msvc2017_64
    BUILD_ARCH: x64

  ##### msvc 2015 ########
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.6\msvc2015
    BUILD_ARCH: x86

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015 Win64"
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.10\msvc2015_64
    BUILD_ARCH: x64

  ##### msvc 2013 ########
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    TOOLCHAIN_VERSION: 12
    QT_ROOT: C:\Qt\5.6\msvc2013
    BUILD_ARCH: x86
    
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 12 2013 Win64"
    TOOLCHAIN_VERSION: 12
    QT_ROOT: C:\Qt\5.6\msvc2013_64
    BUILD_ARCH: x64

matrix:
  fast_finish: false

init:
  #- set varch=%BUILD_ARCH%
  #- if "%BUILD_ARCH%" == "x64" set varch=amd64
  #- if "%BUILD_TARGERT%" == "windows_msvc" if %TOOLCHAIN_VERSION% LSS 15 (call "C:\Program Files (x86)\Microsoft Visual Studio %TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %varch%) else (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %varch%)  
  #- echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  #- echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  #- if NOT "%QT_ROOT%" == "NO" for /f "delims=" %%i in ('%QT_ROOT%/bin/qmake -query QT_VERSION') do (set QT_VERSION=%%i) 
  #- echo QT_ROOT=%QT_ROOT%
  #- echo QT_VERSION=%QT_VERSION%
  #- del C:\msys64\usr\bin\link.exe

install:
  #- C:\msys64\autorebase.bat
  #- C:\msys64\usr\bin\pacman.exe -S --noconfirm unzip
  #- if "%BUILD_TARGERT%"=="windows_mingw" set PATH=C:\Qt\Tools\mingw%TOOLCHAIN_VERSION%_32\bin;%PATH%
  #- if "%BUILD_TARGERT%" == "windows_mingw" set MSYSTEM=MINGW32  #设置编译系统为MINGW32

before_build:

build_script:
  - mkdir build
  - cd build
  - cmake .. -G"%GENERATORS%" -DCMAKE_INSTALL_PREFIX=install
  - cmake --build . --config Release --target install
  - call "C:\Program Files (x86)\NSIS\makensis.exe" "Install.nsi"

artifacts:
  - path: build/ChineseChessCtr-Setup-*.exe

test: off

#See: https://www.appveyor.com/docs/deployment/github/
deploy:
  - provider: GitHub
    #release: FaceRecognizer$(appveyor_build_version)
    #description: 'Release FaceRecognizer $(APPVEYOR_REPO_TAG_NAME) on windows'
    #token : https://github.com/settings/tokens
    #password encrypt: https://ci.appveyor.com/tools/encrypt
    auth_token:
      secure: 2eZXTfGhgCiW9GRLbg9nq7Uz8BVEw4nLzYmgBdvdUIfeEXmlHvC8Xeabsi7yumSx
    #artifact: FaceRecognizer$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(BUILD_ARCH)_$(QT_VERSION)_$(appveyor_build_version)
    #draft: true
    #prerelease: true
    force_update: true
    on:
      BUILD_TARGERT: windows_msvc
      TOOLCHAIN_VERSION: 14
      #QT_VERSION: 5.6.3
      BUILD_ARCH: x86
      appveyor_repo_tag: true        # deploy on tag push only
